version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mypassword
  web:
    build: .
    command: python3 ./manage.py runserver 0.0.0.0:8080
    ports:
      - "8000:8000"
    depends_on:
      - db