version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: python3 ./manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    depends_on:
      - db